### ISSUE TITLE
Possible Weekend Work

### ISSUE THREAD

**Issue by stefsulzer** [stefsulzer/weTravel#1]

**Comment by Meschreiber** [comment]
1) Make sign/up or login from google redirect to a parametrized dashboard
-- taken by MARIA
2) Check if new buddy signing onto a trip is in pending buddies and shoot an error message if not -- taken by Stef
3) Render a change to the buddies list, once a pending buddy is added
4) Better chat stlying 'nuff said
5) Change the styling of timeline
6) Render view-width of timeline activities
7) especially totally optional: research chat bots with firebase, e-mailing, drag and drop, other additional features to come
8) Adding an additional trip
9) From Keziyah: Before adding more features make the site more self-explanatory.  My husband had the same comment.

**Comment by TinaHeiligers** [comment]
Tina: working on 6 in conjunction with delayed rendering.
