### ISSUE TITLE
Fix: Transition to Dashboard from Login and check SignUP

### ISSUE THREAD

**Issue by stefsulzer** [stefsulzer/weTravel#25]
https://www.w3schools.com/bootstrap/bootstrap_modal.asp

**Comment by Meschreiber** [comment]
1) Brand new user:  direct to dashboard --> should display 'Name Your Trip Here!' as the current Trip Name -- once they edit this a new trip is created
2) User with only one trip: directly to dashboard, with trip name displayed
3) User with multiple trips, modal asks to select trip

**Comment by Meschreiber** [comment]
1) set currTrip in users data table from signup, when new trip is created
2) use currTrip in inline buddy edit to draw out buddy information
3) use currTrip in titlebar to render the name
4) update to trip table in inline buddy edit  in addition to the users table
5) rename trip from titlebar --> update trips table
