### ISSUE TITLE
Create timeline component - renders intersection of travel buddy available date

### ISSUE THREAD

**Issue by stefsulzer** [stefsulzer/weTravel#9]

**Comment by TinaHeiligers** [comment]
We've reverted to trying this package: https://github.com/namespace-ee/react-calendar-timeline.
Extra npm style loaders are also required and these have been added to our webpack.config.js file.
It installs and we can plug it into the app and it renders ;-)

**Comment by TinaHeiligers** [comment]
a fix to multiple instances of react loading:
In webpack.config.json, add the following:
```
resolve: {
  alias: {
    react: path.resolve('./node_modules/react'),
  },
},
```
The SO link: http://stackoverflow.com/questions/31169760/how-to-avoid-react-loading-twice-with-webpack-when-developing
